development:
  adapter: postgresql
  encoding: unicode
  database: mquest_development
  pool: 5
  username: postgres
  password: ereinion05

test:
  adapter: postgresql
  encoding: unicode
  database: mquest_test
  pool: 5
  username: postgres
  password: ereinion05