development:
  adapter: postgresql
  encoding: unicode
  database: mquest_development
  pool: 5
  username: postgres
  password: postgres
#  host: 192.168.1.70

test:
  adapter: postgresql
  encoding: unicode
  database: mquest_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: mquest_development
  pool: 5
  username: postgres
  password: postgres