development:
  adapter: postgresql
  encoding: unicode
  database: mquest_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: mquest_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: mquest_development
  pool: 5
  username: postgres
  password: postgres