development:
  bucket: mquestuser
  access_key_id: AKIAIXM2DMH4M2PAT5TA
  secret_access_key: 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
test:
  bucket: mquestuser
  access_key_id: AKIAIXM2DMH4M2PAT5TA
  secret_access_key: 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
production:
  bucket: mquestuser
  access_key_id: AKIAIXM2DMH4M2PAT5TA
  secret_access_key: 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