# development:
#   bucket: mquestuser
#   access_key_id: 
#   secret_access_key: 
# test:
#   bucket: mquestuser
#   access_key_id: 
#   secret_access_key: 
production:
  bucket: mquestuser
  access_key_id: <%= ENV["AMAZON_AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AMAZON_AWS_SECRET_ACCESS_KEY"] %>